name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Gouri4666
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push snake to main branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update snake animation"
          add: "dist/github-contribution-grid-snake.svg"
